# Generated by Django 3.1.3 on 2020-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='user',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
